In [5]:
# pip intall numpy 
#conda intall numpy
import numpy as np

In [6]:
print (type([1,2,3]))
print (type((1,2,3)))
print (type(np.array([1,2,3])))
print (type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
np.zeros(5)# 1 solo numero para un solo arreglo 
np.zeros([5,5])# 1 lista o tupla para una matriz de n dimesiones 
np.zeros((5,5))
np.zeros((2,3,4,5))
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
np.ones (7)
np.ones((1,2,3,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [14]:
np.eye(10)#para hacer una matriz con la diagonal de unos

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.arange(5) # funcion para crear un array incremental

array([0, 1, 2, 3, 4])

In [17]:
np.arange(4,20)# [4,20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(-12,1)#[-12,1[

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [19]:
np.arange(0,20,2)# Del [0,20[ en saltos de dos

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.arange(0,2.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [22]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
np.zeros(20).reshape(2,5,2).reshape(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [27]:
len(np.ones(12))

12

In [28]:
len(np.ones(12).reshape(4,3))

4

In [29]:
#en len cada fila es un elemento

In [30]:
np.ones(12).reshape(4,3).shape#con el shape se tiene el numero de dimesiones

(4, 3)

In [31]:
np.arange(12).reshape(4,3)[1][2]

5

In [32]:
np.array([1,7,12,16]).reshape(2,2)

array([[ 1,  7],
       [12, 16]])

In [34]:
a = np.array([10,10,10])
b = np.array ([5,5,5])

In [35]:
#suma
a+b

array([15, 15, 15])

In [36]:
#resta 
a-b

array([5, 5, 5])

In [37]:
#Multiplicacion
a * b


array([50, 50, 50])

In [38]:
a*3

array([30, 30, 30])

In [39]:
#division
a/2

array([5., 5., 5.])

In [40]:
#Division
a/b

array([2., 2., 2.])

In [42]:
#Operado Modulo
a % 3

array([1, 1, 1], dtype=int32)

In [43]:
a % b

array([0, 0, 0], dtype=int32)

In [44]:
muestra = np.arange(20).reshape(5,2,2)

In [96]:
muestra


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [48]:
respuesta_glucosa = muestra > 5 

In [49]:
respuesta_glucosa


array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [50]:
muestra[respuesta_glucosa]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [104]:
#Mayores a 5 de la glucosa y menore a 14 y que sean pares

mayores_cinco = muestra > 5 
menores_catorce = muestra<14 
par = muestra % 2 == 0 
res = mayores_cinco & menores_catorce & par

In [105]:
muestra[res]

array([ 6,  8, 10, 12])

In [106]:
muestra [(muestra>5)&(muestra<14)&(muestra % 2 == 0)]

array([ 6,  8, 10, 12])